config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :edit, :update]
  resource :session, only: [:new, :create, :destroy]

  resources :messages, only: [:new, :create]

  root 'users#home'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :messages

  validates :age, presence: true

  # def received_messages(params)
  #   self.messages.where(receiver_id: params[:id])
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  # before_action :ensure_current_user, only: [:new, :create, :update, :destroy]

  def current_user
    user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # def ensure_current_user
  #   redirect_to new_session_path unless current_user
  # end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :ensure_current_user

  def new
    @message = Message.new
  end

  def create
    message = Message.new(message_params)
    message.sender = current_user
    if message.save
      redirect_to user_path(message.receiver_id)
    else
    end

  end


  private

  def message_params
    params.require(:message).permit(:content, :receiver_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_current_user

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash.notice = 'Welcome back'
      redirect_to root_path
    else
      flash[:error] = 'Login failed'
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_current_user

  def home
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Thanks for registering"
      session[:user_id] = @user.id
      redirect_to '/users/new'
    else
      render :new
    end
  end

  def show
    @new_message = Message.new
    @user = User.find(params[:id])
    @received_messages = Message.where(receiver_id: params[:id])
  end

  def edit
    @user = User.find(params[:id])

  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :age)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DBCupid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash.any?  %>
    <div id="flash-container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "flash-#{name}" %>
      <% end %>
    </div>
  <% end %>
  <div class="welcome-bar">
    <% if current_user %>
       Welcome <%= current_user.username %>
       <%= link_to 'Log out', session_path, method: :delete %>
    <% else %>
      <nav>
       <%= link_to 'Log in', new_session_path %>|
       <%= link_to 'Register', new_user_path %>
      </nav>
    <% end %>
    <%= link_to 'Home', root_path %>
  </div>
<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>EDIT YOUR PROFILE</h1>
<h3>Please enter some details about yourself</h3>
<h3>This will help people learn a little bit about who you are</h3>

app/views/users/home.html.erb
<h1>WELCOME TO THE HOME PAGE OF DBCupid</h1>

<h2>Here is a list of user profiles for you to visit</h2> <br><br>

<% @users.each do |user| %>
<ul>
  <li><%= link_to user.username, user_path(user)%></li>
</ul>
<%end%>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<fieldset>
  <legend>Please Register</legend>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>
  <div>
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

<% if @user.errors.any? %>
  <div class="error_report">
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>This is the profile of <%=@user.username%></h1>

<p>About Me: <%=@user.about%></p>
<p>Age: <%=@user.age%></p>
<p>Sex: <%=@user.sex%></p>
<p>Horoscope: <%=@user.horoscope%></p>
<p>Education: <%=@user.education%></p>
<p>Diet: <%=@user.diet%></p>
<p>Interests: <%=@user.interests%></p>

<h3>Leave a Message</h3>
  <%= form_for @new_message do |f| %>
    <div>
      <%= f.text_area :content %>
      <%= f.hidden_field :receiver_id, :value => @user.id %>
    </div>
  <%= f.submit %>
<%end%>

<h3>Messages on your wall:</h3><br><br><br>
<% @received_messages.each do |message| %>
  <div>
    <%=message.content%> by <%=message.sender.username%>
  </div>
<%end%>